### ISSUE TITLE
TWILIO

### ISSUE THREAD

**Issue by mraza007** [mraza007/terminal-text#1]
Explore SMPTLIB module to send hassle free texts to phone

**Comment by silvether** [comment]
[SMTPLIB](https://docs.python.org/3/library/smtplib.html) using the below would be a nice alternative to Twilio:

AT&T: [number]@txt.att.net
Sprint: [number]@messaging.sprintpcs.com or [number]@pm.sprint.com
T-Mobile: [number]@tmomail.net
Verizon: [number]@vtext.com
Boost Mobile: [number]@myboostmobile.com
Cricket: [number]@sms.mycricket.com
Metro PCS: [number]@mymetropcs.com
Tracfone: [number]@mmst5.tracfone.com
U.S. Cellular: [number]@email.uscc.net
Virgin Mobile: [number]@vmobl.com

**Comment by mraza007** [comment]
Thanks for adding that I am about to add that
